name: Build and Deploy to Azure

on:
  push:
    branches:
      - main   # or master if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: weatherregistryash123.azurecr.io
          username: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      - run: |
          docker build -t weatherregistryash123.azurecr.io/weather-forecast:latest .
          docker push weatherregistryash123.azurecr.io/weather-forecast:latest

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: weather-forecast-app98765
          images: weatherregistryash123.azurecr.io/weather-forecast:latest
